const path=require('path'),fs=require('fs'),assert=require('assert'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.ART_PLAYWRIGHT||'playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'qa/layout');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),errors=[],results=[];
 try{const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));
 for(const [width,height]of [[900,1100],[540,960],[390,844]]){
  await page.setViewportSize({width,height});await page.goto(pathToFileURL(path.join(root,'index.html')).href);await page.waitForFunction(()=>ART.ready);await page.waitForTimeout(250);
  const title=await page.evaluate(()=>{const h=document.querySelector('.logo h1').getBoundingClientRect(),p=document.querySelector('.logo p').getBoundingClientRect(),screen=topC.getBoundingClientRect();let texts=[];const old=ctx.fillText;ctx.fillText=function(text,...args){texts.push(text);return old.call(this,text,...args);};drawTitle(ctx);ctx.fillText=old;return{gap:p.top-h.bottom,inside:h.left>=screen.left&&h.right<=screen.right,canvasText:texts};});assert(title.gap>0&&title.inside);assert.equal(title.canvasText.length,0);await page.screenshot({path:path.join(out,width+'-title.png')});
  await page.evaluate(()=>{newGameData('탐험가');SET.tips=false;clearPages(TOP);clearPages(BOT);hideMsg();state='intro';introFx={prof:1,mon:1,player:0,pscale:1,white:0};msg('사람들은 몬스터와 함께 생활하고 있단다.',{name:'한결 박사'});});await page.waitForTimeout(250);
  const professor=await page.evaluate(()=>{const p=dpor.getBoundingClientRect(),d=dlg.getBoundingClientRect(),t=dtag.getBoundingClientRect(),s=topC.getBoundingClientRect();return{portraitGap:d.top-p.bottom,tagGap:t.left-p.right,inside:p.top>=s.top&&p.left>=s.left};});assert(professor.portraitGap>0&&professor.tagGap>0&&professor.inside);await page.screenshot({path:path.join(out,width+'-professor.png')});
  await page.evaluate(()=>{state='world';G.party=[makeMon(1,12)];enterMap('home',7,3,'down',{quiet:true});msg('연구소는 마을 위쪽에 있는 큰 건물이야.',{name:'엄마'});});await page.waitForTimeout(250);await page.screenshot({path:path.join(out,width+'-mom.png')});
  await page.evaluate(()=>{hideMsg();enterMap('lab',5,9,'up',{quiet:true});});await page.waitForTimeout(200);await page.screenshot({path:path.join(out,width+'-lab.png')});
  const lab=await page.evaluate(()=>({tables:artFurniture(curMap()).map(b=>[b.w,b.h]),playerSize:(()=>{const c=artTightCell('walk',4);return[26*c.width/c.height,26];})(),rivalSize:(()=>{const c=artTightCell('people',1);return[26*c.width/c.height,26];})(),capsules:STARTERS.filter(([, ,sid])=>!G.flags.starter||(sid!==G.starter&&sid!==G.rivalStarter)).length}));assert.deepEqual(lab.tables,[[3,1],[2,2],[2,2]]);assert.equal(lab.capsules,3);assert.equal(lab.playerSize[1],lab.rivalSize[1]);results.push({width,title,professor,lab});
 }assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({results,errors},null,2));console.log(JSON.stringify({viewports:results.length,errors}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
