// npm install --no-save sharp, then node tools/prepare-art.cjs
// Crops generated atlases; preserves alpha and embeds offline WebP assets.
const fs=require('fs'),path=require('path');
const sharp=require(process.env.ART_SHARP || 'sharp');
const root=path.resolve(__dirname,'..'),dest=path.join(root,'assets','runtime');
fs.mkdirSync(dest,{recursive:true});
const specs={
 monsters:['creatures-front.png',6,6,34,160,160,true],
 backs:['creatures-back.png',6,6,34,160,160,true],
 people:['characters-original.png',7,4,27,128,192,true],
 peopleBack:['characters-back.png',7,4,27,128,192,true],
 walk:['player-motion.png',4,4,16,128,192,true],
 props:['props.png',6,4,24,192,192,true],
 terrain:['terrain.png',4,4,16,128,128,false],
 scenes:['backgrounds.png',3,2,6,512,384,false]
};
// Generated sheets have generous but imperfect gutters. Keep the central
// connected silhouette, removing isolated fragments from a neighbouring cell.
async function cleanCell(buffer){const {data,info}=await sharp(buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true}),w=info.width,h=info.height,labels=new Int32Array(w*h),groups=[];
 for(let start=0;start<w*h;start++){if(labels[start]||data[start*4+3]<50)continue;const label=groups.length+1,queue=[start];labels[start]=label;let minX=w,minY=h,maxX=0,maxY=0;
  for(let q=0;q<queue.length;q++){const at=queue[q],x=at%w,y=Math.floor(at/w);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);
   for(const next of [x?at-1:-1,x<w-1?at+1:-1,y?at-w:-1,y<h-1?at+w:-1])if(next>=0&&!labels[next]&&data[next*4+3]>=50){labels[next]=label;queue.push(next);}
  }groups.push({label,size:queue.length,minX,minY,maxX,maxY});
 }
 const main=groups.sort((a,b)=>b.size-a.size)[0];if(!main)return buffer;
 const keep=new Set(groups.filter(g=>g===main||(g.size>15&&g.minX>=main.minX-3&&g.maxX<=main.maxX+3&&g.minY>=main.minY-3&&g.maxY<=main.maxY+3)).map(g=>g.label));
 for(let i=0;i<w*h;i++)if(!keep.has(labels[i]))data[i*4+3]=0;
 return sharp(data,{raw:info}).png().toBuffer();}
async function main(){const manifest={};
 for(const [key,[file,cols,rows,count,cw,ch,alpha]] of Object.entries(specs)){
  const source=path.join(root,'assets','generated',file),meta=await sharp(source).metadata(),parts=[];
  for(let i=0;i<count;i++){
   const col=i%cols,row=Math.floor(i/cols),left=Math.round(col*meta.width/cols),bounds=key==='props'?[0,314,578,834,meta.height]:null,top=bounds?bounds[row]:Math.round(row*meta.height/rows);
   const special=key==='props'&&i===17?{left:1170,top:660,width:meta.width-1170,height:158}:
    (key==='monsters'||key==='backs')&&i===2?{left:378,top:0,width:265,height:220}:
    key==='monsters'&&i===8?{left:362,top:215,width:278,height:224}:
    key==='backs'&&i===8?{left:378,top:215,width:266,height:224}:
    (key==='monsters'||key==='backs')&&i===23?{left:975,top:640,width:279,height:208}:null; // 바위거북: 머리가 옆 칸까지 나와 있어 넓게
   const box=special||{left,top,width:Math.round((col+1)*meta.width/cols)-left,height:(bounds?bounds[row+1]:Math.round((row+1)*meta.height/rows))-top};
   const revisedSpecies={12:0,21:1,32:2};
   const revised=(key==='monsters'||key==='backs')&&revisedSpecies[i]!==undefined;
   const replacement=path.join(root,'assets','generated','revision-2026-10-11','creature-pairs.png');
   let crop=sharp(source).extract(box);
   if(revised&&fs.existsSync(replacement)){
    const rm=await sharp(replacement).metadata(),column=key==='backs'?1:0,row=revisedSpecies[i];
    const x=Math.round(column*rm.width/2),y=Math.round(row*rm.height/3);
    crop=sharp(replacement).extract({left:x,top:y,width:Math.round((column+1)*rm.width/2)-x,height:Math.round((row+1)*rm.height/3)-y});
   }
   const extracted=await crop.png().toBuffer();crop=sharp(alpha?await cleanCell(extracted):extracted);
   if(alpha)crop=crop.trim({background:'#00000000',threshold:12});
   const buffer=await crop.resize(cw-8,ch-8,{fit:alpha?'contain':'cover',position:alpha?'bottom':'centre',background:'#00000000'}).extend({top:4,bottom:4,left:4,right:4,background:'#00000000'}).png().toBuffer();
   parts.push({input:buffer,left:col*cw,top:row*ch});
  }
  const buffer=await sharp({create:{width:cols*cw,height:rows*ch,channels:4,background:'#00000000'}}).composite(parts).webp({quality:86,alphaQuality:100,effort:6}).toBuffer();
  fs.writeFileSync(path.join(dest,key+'.webp'),buffer);
  manifest[key]={cols,rows,count,cw,ch,src:'data:image/webp;base64,'+buffer.toString('base64')};
  console.log(key,buffer.length);
 }
 fs.writeFileSync(path.join(root,'src','assets25d.js'),'// Generated by tools/prepare-art.cjs; offline asset bundle.\nconst ART_ASSETS='+JSON.stringify(manifest)+';\n');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
